### YamlMime:AzureXplatCli
commands:
- name: create
  description: Creates a new Active Directory application
  usage: '[options] <name> <home-page> <identifier-uris>'
  filePath: commands/arm/ad/ad.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the display name for the application
  - flags: -m --home-page <home-page>
    required: -16
    optional: 0
    bool: True
    short: -m
    long: --home-page
    description: the URL to the application homepage
  - flags: -i --identifier-uris <identifier-uris>
    required: -22
    optional: 0
    bool: True
    short: -i
    long: --identifier-uris
    description: the comma-delimitied URIs that identify the application
  - flags: -l --available <available>
    required: -16
    optional: 0
    bool: True
    short: -l
    long: --available
    description: the value specifying whether the application is a single tenant or a multi-tenant. "true" if the application will be available to other tenants, "false" if its a single tenant application. Default is false.
  - flags: -r --reply-urls <reply-urls>
    required: -17
    optional: 0
    bool: True
    short: -r
    long: --reply-urls
    description: the comma-delimitied application reply urls
  - flags: -p --password <password>
    required: -15
    optional: 0
    bool: True
    short: -p
    long: --password
    description: the value for the password credential associated with the application that will be valid for one year by default
  - flags: --cert-value <cert-value>
    required: -14
    optional: 0
    bool: True
    long: --cert-value
    description: the value of the "asymmetric" credential type. It represents the base 64 encoded certificate.
  - flags: --start-date <start-date>
    required: -14
    optional: 0
    bool: True
    long: --start-date
    description: the start date after which password or key would be valid. Default value is current time
  - flags: --end-date <end-date>
    required: -12
    optional: 0
    bool: True
    long: --end-date
    description: the end date till which password or key is valid. Default value is one year after current time
- name: set
  description: Updates the properties of the created Active Directory application
  usage: '[options]'
  filePath: commands/arm/ad/ad.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -o --objectId <objectId>
    required: -15
    optional: 0
    bool: True
    short: -o
    long: --objectId
    description: the object id of the application to update. Either provide objectId or applicationId. objectId is more preferable.
  - flags: -a --applicationId <applicationId>
    required: -20
    optional: 0
    bool: True
    short: -a
    long: --applicationId
    description: the applicationId of the application to update. If you have created a service principal using this application then this will be the spn of the service principal.
  - flags: -l --available <available>
    required: -16
    optional: 0
    bool: True
    short: -l
    long: --available
    description: the new value specifying whether the application is a single tenant or a multi-tenant. "true" if the application will be available to other tenants, "false" if its a single tenant application.
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the new display name for the application.
  - flags: -m --home-page <home-page>
    required: -16
    optional: 0
    bool: True
    short: -m
    long: --home-page
    description: the new URL to the application homepage
  - flags: -i --identifier-uris <identifier-uris>
    required: -22
    optional: 0
    bool: True
    short: -i
    long: --identifier-uris
    description: new comma-delimitied URI values that identify the application
  - flags: -r --reply-urls <reply-urls>
    required: -17
    optional: 0
    bool: True
    short: -r
    long: --reply-urls
    description: new comma-delimitied application reply urls
  - flags: -p --password <password>
    required: -15
    optional: 0
    bool: True
    short: -p
    long: --password
    description: new value for the password credential associated with the application that will be valid for one year by default
  - flags: --cert-value <cert-value>
    required: -14
    optional: 0
    bool: True
    long: --cert-value
    description: new value of the "asymmetric" credential type. It represents the base 64 encoded certificate.
  - flags: --start-date <start-date>
    required: -14
    optional: 0
    bool: True
    long: --start-date
    description: new start date value after which password or key would be valid. Default value is current time
  - flags: --end-date <end-date>
    required: -12
    optional: 0
    bool: True
    long: --end-date
    description: new end date value till which password or key is valid. Default value is one year after current time
- name: delete
  description: Deletes the Active Directory application
  usage: '[options] <object-id>'
  filePath: commands/arm/ad/ad.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -o --objectId <objectId>
    required: -15
    optional: 0
    bool: True
    short: -o
    long: --objectId
    description: the object id of the application to remove
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode (do not ask for delete confirmation)
- name: list
  description: Get all Active Directory applications in current subscription's tenant
  usage: '[options]'
  filePath: commands/arm/ad/ad.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
- name: show
  description: Get Active Directory applications
  usage: '[options]'
  filePath: commands/arm/ad/ad.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -a --applicationId <applicationId>
    required: -20
    optional: 0
    bool: True
    short: -a
    long: --applicationId
    description: the name of the application to return
  - flags: -o --objectId <objectId>
    required: -15
    optional: 0
    bool: True
    short: -o
    long: --objectId
    description: the object id of the application to return
  - flags: -i --identifierUri <identifierUri>
    required: -20
    optional: 0
    bool: True
    short: -i
    long: --identifierUri
    description: the identifier uri of the application to return
  - flags: -c --search <search>
    required: -13
    optional: 0
    bool: True
    short: -c
    long: --search
    description: search display name of the application starting with the provided value
metadata:
  update_at: 12/30/2016 7:00 AM
  git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/arm/ad/ad.application._js  original_git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/arm/ad/ad.application._js  gitcommit: https://github.com/azure/azure-xplat-cli/lib/commands/arm/ad/ad.application._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: app
description: Commands to display Active Directory applications
usage: '[options] [command]'
