### YamlMime:AzureXplatCli
commands:
- name: create
  description: Generate virtualMachineScaleSetsCreateOrUpdate parameter string or files.
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
- name: patch
  description: Command to patch virtualMachineScaleSetsCreateOrUpdate parameter JSON file.
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --operation <operation>
    required: -13
    optional: 0
    bool: True
    long: --operation
    description: 'The JSON patch operation: add, remove, or replace.'
  - flags: --path <path>
    required: -8
    optional: 0
    bool: True
    long: --path
    description: 'The JSON data path, e.g.: "foo/1".'
  - flags: --value <value>
    required: -9
    optional: 0
    bool: True
    long: --value
    description: The JSON value.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the JSON value to object.
metadata:
  update_at: 12/30/2016 7:30 AM
  git_content_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/arm/compute/virtualMachineScaleSets._js  original_git_content_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/arm/compute/virtualMachineScaleSets._js  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/e782dc553e60b534e9d419a4511a9c54b4a47815/lib/commands/arm/compute/virtualMachineScaleSets._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: config
description: Commands to manage configuration of virtual-machine-scale-sets in the parameter file.
usage: '[options] [command]'
