### YamlMime:AzureXplatCli
commands:
- name: set
  description: "Set windows-profile in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"windowsProfile\" : {\r\n             \"adminUsername\":\"\",\r\n             \"adminPassword\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/containerService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the input string, i.e. str, for parameters to a JSON object, e.g. JSON.parse(str).
  - flags: --admin-username <adminUsername>
    required: -18
    optional: 0
    bool: True
    long: --admin-username
    description: Set the admin-username value.
  - flags: --admin-password <adminPassword>
    required: -18
    optional: 0
    bool: True
    long: --admin-password
    description: Set the admin-password value.
- name: delete
  description: "Remove windows-profile in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"windowsProfile\" : {\r\n             \"adminUsername\":\"\",\r\n             \"adminPassword\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/containerService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --admin-username
    required: 0
    optional: 0
    bool: True
    long: --admin-username
    description: Remove the admin-username value.
  - flags: --admin-password
    required: 0
    optional: 0
    bool: True
    long: --admin-password
    description: Remove the admin-password value.
name: windows-profile
description: Commands to configure windows-profile of acs in config file.
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/acs/config/windows-profile/windows-profile.yml
  update_at: 12/28/2016 2:41 AM
  ms.date: 12/28/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/b5f1f48534a095fdf2852b504110001c0652d8b2/azure-xplat/Azure%20Resource%20Management/acs/config/windows-profile/windows-profile.yml
  ms.topic: reference
