### YamlMime:AzureXplatCli
commands:
- name: show
  description: Get an Application Gateway configuration
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: export
  description: Export Application Gateway configuration to a file
  usage: '[options] <name> <file-path>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -t, --export-to-file <export-to-file>
    required: -22
    optional: 0
    bool: True
    short: -t
    long: --export-to-file
    description: the path to the file where configuration needs to be exported
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: import
  description: Import Application Gateway configuration from a file
  usage: '[options] <name> <import-from-file>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -t, --import-from-file <import-from-file>
    required: -24
    optional: 0
    bool: True
    short: -t
    long: --import-from-file
    description: the path to the configuration file
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: config
description: Commands to manage Application Gateway configuration
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/network/application-gateway/config/config.yml
  update_at: 12/26/2016 8:33 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6e1e5d8c04f7446d91fcaca88663dcd6cdef9a3a/azure-xplat/Azure%20Service%20Management/network/application-gateway/config/config.yml
  ms.topic: reference
