### YamlMime:AzureXplatCli
commands:
- name: set
  description: >-
    Set webapp app settings (using comma seperated key value pairs)

    example:  webapp config appsettings set RGName WebAppName KEY1=val1,KEY2=val2,KEY3=val3
  usage: '[options] <resource-group> <name> <appsettings>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp to show
  - flags: -a --appsettings <appsettings>
    required: -18
    optional: 0
    bool: True
    short: -a
    long: --appsettings
    description: the appsettings of the webapp to add
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: delete
  description: >-
    Delete webapp app settings (using comma seperated keys)

    example:  webapp config appsettings delete RGName WebAppName KEY1,KEY2,KEY3
  usage: '[options] <resource-group> <name> <appsettings>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp to show
  - flags: -a --appsettings <appsettings>
    required: -18
    optional: 0
    bool: True
    short: -a
    long: --appsettings
    description: the appsettings of the webapp to delete
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: list
  description: Get webapp app settings
  usage: '[options] <resource-group> <name>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp to list
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: appsettings
description: Commands to manage your Azure webapps app setting configurations
usage: '[options] [command]'
Metadata:
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/webapp/config/appsettings/appsettings.yml
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/webapp/config/appsettings/appsettings.yml
  update_at: 12/26/2016 5:40 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/b1f9f2de97a35fb1e5a719e3e38a2f2848bfe692/azure-xplat/Azure%20Resource%20Management/webapp/config/appsettings/appsettings.yml
  ms.topic: reference
  ms.prod: 
  ms.technology: 
  author
  ms.author
  keywords
  manager
