### YamlMime:AzureXplatCli
commands:
- name: create
  description: Create a cloud service
  usage: '[options] <serviceName>'
  filePath: commands/asm/service._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --serviceName <serviceName>
    required: -15
    optional: 0
    bool: True
    long: --serviceName
    description: the cloud service name
  - flags: --description <description>
    required: -15
    optional: 0
    bool: True
    long: --description
    description: the description. Defaults to 'Service host'
  - flags: --location <location>
    required: -12
    optional: 0
    bool: True
    long: --location
    description: the location. Optional if affinitygroup is specified
  - flags: --affinitygroup <affinitygroup>
    required: -17
    optional: 0
    bool: True
    long: --affinitygroup
    description: the affinity group. Optional if location is specified
  - flags: --label <label>
    required: -9
    optional: 0
    bool: True
    long: --label
    description: the label. Defaults to serviceName
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: list
  description: List Azure cloud services
  usage: '[options]'
  filePath: commands/asm/service._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: show
  description: Show Azure cloud service. Provides detailed information about deployments when used with --json option.
  usage: '[options] <serviceName>'
  filePath: commands/asm/service._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --serviceName <serviceName>
    required: -15
    optional: 0
    bool: True
    long: --serviceName
    description: the cloud service name
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: delete
  description: Delete a cloud service
  usage: '[options] <serviceName>'
  filePath: commands/asm/service._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --serviceName <serviceName>
    required: -15
    optional: 0
    bool: True
    long: --serviceName
    description: the cloud service name
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode, do not ask for delete confirmation
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: get-deployment-event
  description: Get details of deployment events.
  usage: '[options] <serviceName> <startTime> <endTime>'
  filePath: commands/asm/service._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --service-name <service-name>
    required: -16
    optional: 0
    bool: True
    long: --service-name
    description: the cloud service name
  - flags: -d, --deployment-name <deployment-name>
    required: -23
    optional: 0
    bool: True
    short: -d
    long: --deployment-name
    description: the deployment name
  - flags: -t, --start-time <start-time>
    required: -18
    optional: 0
    bool: True
    short: -t
    long: --start-time
    description: the start time specified in UTC e.g. 2015-06-17T17:58:50.4290652Z, 2015-06-17
  - flags: -e, --end-time <end-time>
    required: -16
    optional: 0
    bool: True
    short: -e
    long: --end-time
    description: the end time specified in UTC
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
name: service
description: Commands to manage your Cloud Services
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/service/service.yml
  update_at: 12/26/2016 8:07 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6160027b77dbfdec40c6aee3f83b1ab23cc14628/azure-xplat/Azure%20Service%20Management/service/service.yml
  ms.topic: reference
  ms.prod: 
  ms.technology: 
  author
  ms.author
  keywords
  manager
