### YamlMime:AzureXplatCli
commands: []
metadata: {}
name: package
description: Commands to send your service package
usage: '[options]'
Metadata:
  update_at: 12/30/2016 7:23 AM
  open_to_public_contributors: false
  ms.date: 12/30/2016
  ms.topic: reference