### YamlMime:AzureXplatCli
commands:
- name: create
  description: Creates a persisted Azure HDInsight cluster configuration file.
  usage: '[options] <configFilePath> <overwrite>'
  filePath: commands/arm/hdinsight/hdinsight._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --configFilePath <configFilePath>
    required: -18
    optional: 0
    bool: True
    long: --configFilePath
    description: HdInsight configuration file path
  - flags: --overwrite <overwrite>
    required: -13
    optional: 0
    bool: True
    long: --overwrite
    description: Overwrites existing configuration file
- name: add-config-values
  description: Adds a Hadoop configuration value customization or a Hive shared library customization to an HDInsight cluster configuration. Each component config is in the format of 'name=value'. For example, parameter1=value1;parameter2=value2
  usage: '[options] <configFilePath>'
  filePath: commands/arm/hdinsight/hdinsight._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --configFilePath <configFilePath>
    required: -18
    optional: 0
    bool: True
    long: --configFilePath
    description: Configuration file path
  - flags: --core-site <core-site>
    required: -13
    optional: 0
    bool: True
    long: --core-site
    description: Config values in the format of 'name=value'
  - flags: --hive-site <hive-site>
    required: -13
    optional: 0
    bool: True
    long: --hive-site
    description: Config values in the format of 'name=value'
  - flags: --hive-env <hive-env>
    required: -12
    optional: 0
    bool: True
    long: --hive-env
    description: Config values in the format of 'name=value'
  - flags: --hdfs-site <hdfs-site>
    required: -13
    optional: 0
    bool: True
    long: --hdfs-site
    description: Config values in the format of 'name=value'
  - flags: --hbase-env <hbase-env>
    required: -13
    optional: 0
    bool: True
    long: --hbase-env
    description: Config values in the format of 'name=value'
  - flags: --hbase-site <hbase-site>
    required: -14
    optional: 0
    bool: True
    long: --hbase-site
    description: Config values in the format of 'name=value'
  - flags: --mapred-site <mapred-site>
    required: -15
    optional: 0
    bool: True
    long: --mapred-site
    description: Config values in the format of 'name=value'
  - flags: --oozie-env <oozie-env>
    required: -13
    optional: 0
    bool: True
    long: --oozie-env
    description: Config values in the format of 'name=value'
  - flags: --oozie-site <oozie-site>
    required: -14
    optional: 0
    bool: True
    long: --oozie-site
    description: Config values in the format of 'name=value'
  - flags: --storm-site <storm-site>
    required: -14
    optional: 0
    bool: True
    long: --storm-site
    description: Config values in the format of 'name=value'
  - flags: --tez-site <tez-site>
    required: -12
    optional: 0
    bool: True
    long: --tez-site
    description: Config values in the format of 'name=value'
  - flags: --webhcat-site <webhcat-site>
    required: -16
    optional: 0
    bool: True
    long: --webhcat-site
    description: Config values in the format of 'name=value'
  - flags: --gateway <gateway>
    required: -11
    optional: 0
    bool: True
    long: --gateway
    description: Config values in the format of 'name=value'
  - flags: --yarn <yarn>
    required: -8
    optional: 0
    bool: True
    long: --yarn
    description: Config values in the format of 'name=value'
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: The subscription id
- name: add-script-action
  description: Adds a HDInsight script action.
  usage: '[options] <configFilePath>'
  filePath: commands/arm/hdinsight/hdinsight._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --configFilePath <configFilePath>
    required: -18
    optional: 0
    bool: True
    long: --configFilePath
    description: Configuration file path
  - flags: --nodeType <nodeType>
    required: -12
    optional: 0
    bool: True
    long: --nodeType
    description: 'Specifies the node on which this cmdlet applies the action. Supported node types: HeadNode | WorkerNode | ZookeeperNode'
  - flags: --uri <uri>
    required: -7
    optional: 0
    bool: True
    long: --uri
    description: Specifies the URI for the action
  - flags: --name <name>
    required: -8
    optional: 0
    bool: True
    long: --name
    description: Specifies the name of the action
  - flags: --parameters <parameters>
    required: -14
    optional: 0
    bool: True
    long: --parameters
    description: Specifies the parameters for the action
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: The subscription id
name: config
description: Commands to manage HDInsight cluster configuration
usage: '[options] [command]'
Metadata:
  update_at: 12/30/2016 7:37 AM
  open_to_public_contributors: false
  ms.date: 12/30/2016
  ms.topic: reference