### YamlMime:AzureXplatCli
commands:
- name: create
  description: Creates an application package record
  usage: '[options] [resource-group] [account-name] [application-id] [version] [package-file]'
  filePath: commands/batch/batch.applicationPackage._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --version <version>
    required: -11
    optional: 0
    bool: True
    long: --version
    description: the version of the application
  - flags: --package-file <package-file>
    required: -16
    optional: 0
    bool: True
    long: --package-file
    description: the application package in zip format
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: delete
  description: Deletes an application package record
  usage: '[options] [resource-group] [account-name] [application-id] [version]'
  filePath: commands/batch/batch.applicationPackage._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --version <version>
    required: -11
    optional: 0
    bool: True
    long: --version
    description: the version of the application to delete
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: delete the specified application package without confirmation
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: show
  description: Show details of the Batch application package
  usage: '[options] [resource-group] [account-name] [application-id] [version]'
  filePath: commands/batch/batch.applicationPackage._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --version <version>
    required: -11
    optional: 0
    bool: True
    long: --version
    description: the version of the application to show
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: activate
  description: Activate an application package
  usage: '[options] [resource-group] [account-name] [application-id] [version] [format]'
  filePath: commands/batch/batch.applicationPackage._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --version <version>
    required: -11
    optional: 0
    bool: True
    long: --version
    description: the version of the application to activate
  - flags: --format <format>
    required: -10
    optional: 0
    bool: True
    long: --format
    description: the format of the application package binary file
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
metadata:
  update_at: 12/30/2016 4:53 AM  git_content_url:git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/batch/batch.applicationPackage._js  original_git_content_url:git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/batch/batch.applicationPackage._js  gitcommit:git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/batch/batch.applicationPackage._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: package
description: Commands to manage your Batch Application Package
usage: '[options] [command]'
