### YamlMime:AzureXplatCli
commands:
- name: add
  description: Add a backend address pool to an Application Gateway
  usage: '[options] <gateway-name> <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the Application Gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the HTTP settings
  - flags: -p, --protocol <protocol>
    required: -16
    optional: 0
    bool: True
    short: -p
    long: --protocol
    description: the protocol, valid value is [Http]
  - flags: -o, --port <port>
    required: -12
    optional: 0
    bool: True
    short: -o
    long: --port
    description: the port, valid range is [0-65535]
  - flags: -c, --cookie-based-affinity <cookie-based-affinity>
    required: -29
    optional: 0
    bool: True
    short: -c
    long: --cookie-based-affinity
    description: >-
      Enable or disable cookie based affinity, valid values are
           [Disabled,Enabled],
           default value is Disabled
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: remove
  description: Remove a backend address pool to an Application Gateway
  usage: '[options] <gateway-name> <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the Application Gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the HTTP settings
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode, do not ask for unregister confirmation
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: http-settings
description: Commands to manage Application Gateway http settings
usage: '[options] [command]'
Metadata:
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/network/application-gateway/http-settings/http-settings.yml
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/network/application-gateway/http-settings/http-settings.yml
  update_at: 12/26/2016 5:26 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/ae01dbd5c15db8c858fc982274228402c00f8eda/azure-xplat/Azure%20Service%20Management/network/application-gateway/http-settings/http-settings.yml
