### YamlMime:AzureXplatCli
commands:
- name: create
  description: Adds an application to the specified Batch account
  usage: '[options] [resource-group] [account-name] [application-id]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --allow-updates <allow-updates>
    required: -17
    optional: 0
    bool: True
    long: --allow-updates
    description: whether packages within the application may be overwritten using the same version string
  - flags: --display-name <display-name>
    required: -16
    optional: 0
    bool: True
    long: --display-name
    description: the display name for the application
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: set
  description: Updates an application to the specified Batch account
  usage: '[options] [resource-group] [account-name] [application-id]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: --allow-updates <allow-updates>
    required: -17
    optional: 0
    bool: True
    long: --allow-updates
    description: whether packages within the application may be overwritten using the same version string
  - flags: --display-name <display-name>
    required: -16
    optional: 0
    bool: True
    long: --display-name
    description: the display name for the application
  - flags: --default-version <default-version>
    required: -19
    optional: 0
    bool: True
    long: --default-version
    description: the package to use if a client requests the application but does not specify a version
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: delete
  description: Deletes an application
  usage: '[options] [resource-group] [account-name] [application-id]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: delete the specified application without confirmation
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: show
  description: Show details of the Batch application
  usage: '[options] [resource-group] [account-name] [application-id]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: list
  description: Lists all of the applications in the specified account
  usage: '[options] [resource-group] [account-name]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --account-name <account-name>
    required: -16
    optional: 0
    bool: True
    long: --account-name
    description: the name of the Batch account
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the resource group name
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: list-summary
  description: Lists all of the applications available in the specified account
  usage: '[options]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -a, --account-name <account-name>
    required: -20
    optional: 0
    bool: True
    short: -a
    long: --account-name
    description: the Batch account name
  - flags: -k, --account-key <account-key>
    required: -19
    optional: 0
    bool: True
    short: -k
    long: --account-key
    description: the Batch account key
  - flags: -u, --account-endpoint <account-endpoint>
    required: -24
    optional: 0
    bool: True
    short: -u
    long: --account-endpoint
    description: the Batch account URL
- name: show-summary
  description: Show details of the application in the specified account
  usage: '[options] [application-id]'
  filePath: commands/batch/batch.application._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --application-id <application-id>
    required: -18
    optional: 0
    bool: True
    long: --application-id
    description: the id of the application
  - flags: -a, --account-name <account-name>
    required: -20
    optional: 0
    bool: True
    short: -a
    long: --account-name
    description: the Batch account name
  - flags: -k, --account-key <account-key>
    required: -19
    optional: 0
    bool: True
    short: -k
    long: --account-key
    description: the Batch account key
  - flags: -u, --account-endpoint <account-endpoint>
    required: -24
    optional: 0
    bool: True
    short: -u
    long: --account-endpoint
    description: the Batch account URL
name: application
description: Commands to manage your Batch Application
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/batch/application/application.yml
  update_at: 12/26/2016 8:33 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6e1e5d8c04f7446d91fcaca88663dcd6cdef9a3a/azure-xplat/Azure%20Resource%20Management/batch/application/application.yml
  ms.topic: reference
