### YamlMime:AzureXplatCli
commands:
- name: create
  description: Create an Application Gateway
  usage: '[options] <name> <vnet-name> <subnet-name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -e, --vnet-name <vnet-name>
    required: -17
    optional: 0
    bool: True
    short: -e
    long: --vnet-name
    description: the name of the virtual network Application Gateway should be deployed in
  - flags: -t, --subnet-name <subnet-name>
    required: -19
    optional: 0
    bool: True
    short: -t
    long: --subnet-name
    description: the name of subnet which exists in same vnet
  - flags: -c, --instance-count <instance-count>
    required: -22
    optional: 0
    bool: True
    short: -c
    long: --instance-count
    description: the number of instances
  - flags: -z, --gateway-size <gateway-size>
    required: -20
    optional: 0
    bool: True
    short: -z
    long: --gateway-size
    description: size of the Application Gateway, valid values are [Small,Medium,Large,ExtraLarge,A8]
  - flags: -d, --description <description>
    required: -19
    optional: 0
    bool: True
    short: -d
    long: --description
    description: the description for the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: set
  description: Set an Application Gateway
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -e, --vnet-name <vnet-name>
    required: -17
    optional: 0
    bool: True
    short: -e
    long: --vnet-name
    description: the name of the virtual network Application Gateway should be deployed in
  - flags: -t, --subnet-name <subnet-name>
    required: -19
    optional: 0
    bool: True
    short: -t
    long: --subnet-name
    description: the name of subnet which exists in same vnet
  - flags: -c, --instance-count <instance-count>
    required: -22
    optional: 0
    bool: True
    short: -c
    long: --instance-count
    description: the number of instances
  - flags: -z, --gateway-size <gateway-size>
    required: -20
    optional: 0
    bool: True
    short: -z
    long: --gateway-size
    description: size of the Application Gateway, valid values are [Small,Medium,Large,ExtraLarge,A8]
  - flags: -d, --description <description>
    required: -19
    optional: 0
    bool: True
    short: -d
    long: --description
    description: the description for the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: list
  description: Get all Application Gateways
  usage: '[options]'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: show
  description: Get an Application Gateway
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: delete
  description: Delete an Application Gateway
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode, do not ask for delete confirmation
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: start
  description: Start an Application Gateway
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: stop
  description: Stop an Application Gateway
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
metadata:
  update_at: 12/30/2016 7:23 AM
  git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/asm/network/network._js  original_git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/asm/network/network._js  gitcommit: https://github.com/azure/azure-xplat-cli/lib/commands/asm/network/network._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: application-gateway
description: Commands to manage Application Gateway
usage: '[options] [command]'
