### YamlMime:AzureXplatCli
commands:
- name: set
  description: "Set agent-pool-profiles in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"agentPoolProfiles\" : {\r\n             \"name\":\"\",\r\n             \"count\":null,\r\n             \"vmSize\":\"\",\r\n             \"dnsPrefix\":\"\",\r\n             \"fqdn\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/containerService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --index <index>
    required: -9
    optional: 0
    bool: True
    long: --index
    description: 'Indexer: index.'
  - flags: --value <value>
    required: -9
    optional: 0
    bool: True
    long: --value
    description: The input string value for the indexed item.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the input string, i.e. str, for parameters to a JSON object, e.g. JSON.parse(str).
  - flags: --name <name>
    required: -8
    optional: 0
    bool: True
    long: --name
    description: Set the name value.
  - flags: --count <count>
    required: -9
    optional: 0
    bool: True
    long: --count
    description: Set the count value.
  - flags: --vm-size <vmSize>
    required: -11
    optional: 0
    bool: True
    long: --vm-size
    description: Set the vm-size value.
  - flags: --dns-prefix <dnsPrefix>
    required: -14
    optional: 0
    bool: True
    long: --dns-prefix
    description: Set the dns-prefix value.
  - flags: --fqdn <fqdn>
    required: -8
    optional: 0
    bool: True
    long: --fqdn
    description: Set the fqdn value.
- name: delete
  description: "Remove agent-pool-profiles in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"agentPoolProfiles\" : {\r\n             \"name\":\"\",\r\n             \"count\":null,\r\n             \"vmSize\":\"\",\r\n             \"dnsPrefix\":\"\",\r\n             \"fqdn\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/containerService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --index <index>
    required: -9
    optional: 0
    bool: True
    long: --index
    description: 'Indexer: index.'
  - flags: --name
    required: 0
    optional: 0
    bool: True
    long: --name
    description: Remove the name value.
  - flags: --count
    required: 0
    optional: 0
    bool: True
    long: --count
    description: Remove the count value.
  - flags: --vm-size
    required: 0
    optional: 0
    bool: True
    long: --vm-size
    description: Remove the vm-size value.
  - flags: --dns-prefix
    required: 0
    optional: 0
    bool: True
    long: --dns-prefix
    description: Remove the dns-prefix value.
  - flags: --fqdn
    required: 0
    optional: 0
    bool: True
    long: --fqdn
    description: Remove the fqdn value.
name: agent-pool-profiles
description: Commands to configure agent-pool-profiles of acs in config file.
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/acs/config/agent-pool-profiles/agent-pool-profiles.yml
  update_at: 12/26/2016 8:07 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6160027b77dbfdec40c6aee3f83b1ab23cc14628/azure-xplat/Azure%20Resource%20Management/acs/config/agent-pool-profiles/agent-pool-profiles.yml
  ms.topic: reference
  ms.prod: 
  ms.technology: 
  author
  ms.author
  keywords
  manager
