### YamlMime:AzureXplatCli
commands:
- name: list
  description: Show your site application settings (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
  usage: '[options] [name]'
  filePath: commands/asm/site.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: add
  description: Add an application setting for your site (for values containing the character ';', use quotes in the format of "\"value\"". e.g. SB_CONN="\"Endpoint=sb://namespace.servicebus.windows.net/;SharedSecretIssuer=owner"\") (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
  usage: '[options] <keyvaluepair> [name]'
  filePath: commands/asm/site.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: clear
  description: Clear an application setting for your site (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
  usage: '[options] <key> [name]'
  filePath: commands/asm/site.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: get
  description: Get an application setting for your site (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
  usage: '[options] <key> [name]'
  filePath: commands/asm/site.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
name: config
description: Commands to manage your Web Site configurations (deprecated. This command is deprecated and will be removed in a future version. Please use "site appsetting" instead
usage: '[options] [command]'
Metadata:
  ms.topic: reference
  open_to_public_contributors: true
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/asm/site.config._js
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/asm/site.config._js
  update_at: 3/24/2014 11:13 PM
  ms.date: 3/24/2014
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/8d1dd46ff12851698b14f49e42abe42f83bb4fcd/lib/commands/asm/site.config._js

