### YamlMime:AzureXplatCli
commands:
- name: list
  description: Show your mobile service configuration settings
  usage: '[options] [servicename]'
  filePath: commands/asm/mobile._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: set
  description: Set a mobile service configuration setting
  usage: '[options] <servicename> <key> [value]'
  filePath: commands/asm/mobile._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -f, --file <file>
    required: -12
    optional: 0
    bool: True
    short: -f
    long: --file
    description: read the value of the setting from a file
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
- name: get
  description: Get a mobile service configuration setting
  usage: '[options] [servicename] [key]'
  filePath: commands/asm/mobile._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -f, --file <file>
    required: -12
    optional: 0
    bool: True
    short: -f
    long: --file
    description: save the value of the setting to a file
  - flags: -s, --subscription <id>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription id
name: config
description: Commands to manage your Mobile Service configuration
usage: '[options] [command]'
Metadata:
  update_at: 12/30/2016 7:37 AM
  open_to_public_contributors: false
  ms.date: 12/30/2016
  ms.topic: reference