### YamlMime:AzureXplatCli
commands:
- name: create
  description: Create an application gateway web application firewall config
  usage: '[options] <resource-group> <gateway-name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -m, --waf-mode [waf-mode]
    required: 0
    optional: -16
    bool: True
    short: -m
    long: --waf-mode
    description: >-
      Mode of web application firewall for application gateway
            supported values are [Detection,Prevention]
  - flags: -e, --enable [enable]
    required: 0
    optional: -14
    bool: True
    short: -e
    long: --enable
    description: >-
      If web application firewall enabled on application gateway
            supported values are [true, false]
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: show
  description: Show an application gateway web application firewall config
  usage: '[options] <resource-group> <gateway-name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: delete
  description: Delete an application gateway web application firewall config
  usage: '[options] <resource-group> <gateway-name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode, do not ask for delete confirmation
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: waf-config
description: Commands to manage application gateway web application firewall configuration
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/network/application-gateway/waf-config/waf-config.yml
  update_at: 12/26/2016 8:33 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6e1e5d8c04f7446d91fcaca88663dcd6cdef9a3a/azure-xplat/Azure%20Resource%20Management/network/application-gateway/waf-config/waf-config.yml
  ms.topic: reference
