### YamlMime:AzureXplatCli
commands:
- name: create
  description: Add http settings to an application gateway
  usage: '[options] <resource-group> <gateway-name> <name> <port>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the HTTP settings
  - flags: -p, --protocol [protocol]
    required: 0
    optional: -16
    bool: True
    short: -p
    long: --protocol
    description: the protocol, valid value is [http]
  - flags: -o, --port <port>
    required: -12
    optional: 0
    bool: True
    short: -o
    long: --port
    description: the port, valid range is [0,65535]
  - flags: -c, --cookie-based-affinity [cookie-based-affinity]
    required: 0
    optional: -29
    bool: True
    short: -c
    long: --cookie-based-affinity
    description: >-
      enable or disable cookie based affinity, valid values are
           [Disabled,Enabled],
           default value is [Disabled]
  - flags: -r, --probe-name [probe-name]
    required: 0
    optional: -18
    bool: True
    short: -r
    long: --probe-name
    description: specified application gateway probe name
  - flags: -i, --probe-id [probe-id]
    required: 0
    optional: -16
    bool: True
    short: -i
    long: --probe-id
    description: application gateway probe ID
  - flags: --nowait
    required: 0
    optional: 0
    bool: True
    long: --nowait
    description: does not wait for the operation to complete. Returns as soon as the intial request is received by the server.
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: set
  description: Update http settings of an application gateway
  usage: '[options] <resource-group> <gateway-name> <name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the HTTP settings
  - flags: -p, --protocol [protocol]
    required: 0
    optional: -16
    bool: True
    short: -p
    long: --protocol
    description: the protocol, valid value is [http]
  - flags: -o, --port [port]
    required: 0
    optional: -12
    bool: True
    short: -o
    long: --port
    description: the port, valid range is [0,65535]
  - flags: -c, --cookie-based-affinity [cookie-based-affinity]
    required: 0
    optional: -29
    bool: True
    short: -c
    long: --cookie-based-affinity
    description: >-
      enable or disable cookie based affinity, valid values are
           [Disabled,Enabled],
           default value is [Disabled]
  - flags: -r, --probe-name [probe-name]
    required: 0
    optional: -18
    bool: True
    short: -r
    long: --probe-name
    description: specified application gateway probe name
  - flags: -i, --probe-id [probe-id]
    required: 0
    optional: -16
    bool: True
    short: -i
    long: --probe-id
    description: application gateway probe ID
  - flags: --nowait
    required: 0
    optional: 0
    bool: True
    long: --nowait
    description: does not wait for the operation to complete. Returns as soon as the intial request is received by the server.
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: show
  description: Show a http settings from an application gateway
  usage: '[options] <resource-group> <gateway-name> <name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the http settings
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: list
  description: List an application gateway http settings
  usage: '[options] <resource-group> <gateway-name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: delete
  description: Delete http settings to an application gateway
  usage: '[options] <resource-group> <gateway-name> <name>'
  filePath: commands/arm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g, --resource-group <resource-group>
    required: -22
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -w, --gateway-name <gateway-name>
    required: -20
    optional: 0
    bool: True
    short: -w
    long: --gateway-name
    description: the name of the application gateway
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the HTTP settings
  - flags: -q, --quiet
    required: 0
    optional: 0
    bool: True
    short: -q
    long: --quiet
    description: quiet mode, do not ask for unregister confirmation
  - flags: --nowait
    required: 0
    optional: 0
    bool: True
    long: --nowait
    description: does not wait for the operation to complete. Returns as soon as the intial request is received by the server.
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
metadata:
  update_at: 12/30/2016 7:00 AM
  git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/arm/network/network._js  original_git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/arm/network/network._js  gitcommit: https://github.com/azure/azure-xplat-cli/lib/commands/arm/network/network._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: http-settings
description: Commands to manage application gateway http settings
usage: '[options] [command]'
