### YamlMime:AzureXplatCli
commands: []
name: package
description: Commands to manage your code package
usage: '[options]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/servicefabric/code/package.yml
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob//azure-xplat/Azure%20Service%20Management/servicefabric/code/package.yml
  ms.topic: reference
