### YamlMime:AzureXplatCli
commands:
- name: show
  description: Show application
  usage: '[options]'
  filePath: commands/servicefabric/serviceFabricApplication._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --application-name <applicationName>
    required: -23
    optional: 0
    bool: True
    short: -n
    long: --application-name
    description: the name of the application
  - flags: --select <fields>
    required: -10
    optional: 0
    bool: True
    long: --select
    description: select fields to show, call without this parameter to see all fields
- name: create
  description: 'Create application, Example: azure servicefabric application create --application-name fabric:/app --application-type-name type1 --application-type-version 1.0'
  usage: '[options] [applicationName] [applicationTypeName] [applicationTypeVersion]'
  filePath: commands/servicefabric/serviceFabricApplication._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --application-name <applicationName>
    required: -23
    optional: 0
    bool: True
    short: -n
    long: --application-name
    description: the name of the application
  - flags: -t --application-type-name <applicationTypeName>
    required: -28
    optional: 0
    bool: True
    short: -t
    long: --application-type-name
    description: the name of the application type
  - flags: -a --application-type-version <applicationTypeVersion>
    required: -31
    optional: 0
    bool: True
    short: -a
    long: --application-type-version
    description: the version of the application type
  - flags: -p --application-parameter <applicationParameter>
    required: -28
    optional: 0
    bool: True
    short: -p
    long: --application-parameter
    description: 'the parameter of the application, json string "{"Key": "key1", "Value": "value1"}"'
- name: delete
  description: Delete application
  usage: '[options] [applicationName]'
  filePath: commands/servicefabric/serviceFabricApplication._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --application-name <applicationName>
    required: -23
    optional: 0
    bool: True
    short: -n
    long: --application-name
    description: the name of the application
metadata:
  update_at: 12/30/2016 7:23 AM
  git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/servicefabric/serviceFabricApplication._js  original_git_content_url: https://github.com/azure/azure-xplat-cli/lib/commands/servicefabric/serviceFabricApplication._js  gitcommit: https://github.com/azure/azure-xplat-cli/lib/commands/servicefabric/serviceFabricApplication._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: application
description: Commands to manage your application
usage: '[options] [command]'
