### YamlMime:AzureXplatCli
commands:
- name: show
  description: Show service
  usage: '[options] [applicationName]'
  filePath: commands/servicefabric/serviceFabricService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --application-name <serviceName>
    required: -23
    optional: 0
    bool: True
    short: -n
    long: --application-name
    description: the name of the application
  - flags: -e --service-name <serviceName>
    required: -19
    optional: 0
    bool: True
    short: -e
    long: --service-name
    description: the name of the service
  - flags: --select <fields>
    required: -10
    optional: 0
    bool: True
    long: --select
    description: select fields to show, call without this parameter to see all fields
- name: create
  description: 'Create service, Example: servicefabric service create --application-name fabric:/app --service-name fabric:/app/service --service-type-name ServiceType1 --service-kind Stateless --instance-count 1 --partition-scheme Singleton'
  usage: '[options] [applicationName] [serviceName] [serviceTypeName] [serviceKind] [partitionScheme]'
  filePath: commands/servicefabric/serviceFabricService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --application-name <applicationName>
    required: -23
    optional: 0
    bool: True
    short: -n
    long: --application-name
    description: the name of the application
  - flags: -e --service-name <serviceName>
    required: -19
    optional: 0
    bool: True
    short: -e
    long: --service-name
    description: the name of the service
  - flags: -t --service-type-name <serviceTypeName>
    required: -24
    optional: 0
    bool: True
    short: -t
    long: --service-type-name
    description: the name of the service type
  - flags: -k --service-kind <serviceKind>
    required: -19
    optional: 0
    bool: True
    short: -k
    long: --service-kind
    description: the kind of the service, values are [Stateless|Stateful]
  - flags: -c --instance-count <instanceCount>
    required: -21
    optional: 0
    bool: True
    short: -c
    long: --instance-count
    description: the count of the instance
  - flags: -r --target-replica-set-size <targetReplicaSetSize>
    required: -30
    optional: 0
    bool: True
    short: -r
    long: --target-replica-set-size
    description: the size of the target replica set
  - flags: -m --min-replica-set-size <minReplicaSetSize>
    required: -27
    optional: 0
    bool: True
    short: -m
    long: --min-replica-set-size
    description: the size of the min replica set
  - flags: -p --has-persisted-state
    required: 0
    optional: 0
    bool: True
    short: -p
    long: --has-persisted-state
    description: the state of the persisted
  - flags: -a --partition-scheme <partitionScheme>
    required: -23
    optional: 0
    bool: True
    short: -a
    long: --partition-scheme
    description: the scheme of the partition
  - flags: -i --partition-count <partitionCount>
    required: -22
    optional: 0
    bool: True
    short: -i
    long: --partition-count
    description: the count of the partition
  - flags: -o --partition-names <partitionNames>
    required: -22
    optional: 0
    bool: True
    short: -o
    long: --partition-names
    description: the names of the partition
  - flags: -l --partition-low-key <partitionLowKey>
    required: -24
    optional: 0
    bool: True
    short: -l
    long: --partition-low-key
    description: the key of the partition low
  - flags: -g --partition-high-key <partitionHighKey>
    required: -25
    optional: 0
    bool: True
    short: -g
    long: --partition-high-key
    description: the key of the partition high
  - flags: -b --placement-constraints <placementConstraints>
    required: -28
    optional: 0
    bool: True
    short: -b
    long: --placement-constraints
    description: the constraints of the placement
  - flags: -c --correlation-schema <correlationSchema>
    required: -25
    optional: 0
    bool: True
    short: -c
    long: --correlation-schema
    description: the schema of the correlation, json string
  - flags: -d --service-load-metrics <serviceLoadMetrics>
    required: -27
    optional: 0
    bool: True
    short: -d
    long: --service-load-metrics
    description: the metrics of the service load, json string
  - flags: -f --service-placement-policy-description <servicePlacementPolicyDescription>
    required: -43
    optional: 0
    bool: True
    short: -f
    long: --service-placement-policy-description
    description: the description of the service placement policy, json string
- name: update
  description: 'Update service, Example: azure servicefabric service update --service-name fabric:/app --instance-count 1'
  usage: '[options] [serviceName] [serviceKind]'
  filePath: commands/servicefabric/serviceFabricService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --service-name <serviceName>
    required: -19
    optional: 0
    bool: True
    short: -n
    long: --service-name
    description: the name of the service
  - flags: -k --service-kind <serviceKind>
    required: -19
    optional: 0
    bool: True
    short: -k
    long: --service-kind
    description: the kind of the service, values are [Stateless|Stateful]
  - flags: -c --instance-count <instanceCount>
    required: -21
    optional: 0
    bool: True
    short: -c
    long: --instance-count
    description: the count of the instance
  - flags: -r --target-replica-set-size <targetReplicaSetSize>
    required: -30
    optional: 0
    bool: True
    short: -r
    long: --target-replica-set-size
    description: the size of the target replica set
  - flags: -m --min-replica-set-size <minReplicaSetSize>
    required: -27
    optional: 0
    bool: True
    short: -m
    long: --min-replica-set-size
    description: the size of the min replica set
  - flags: -i --replica-restart-wait-duration-in-milliseconds <replicaRestartWaitDurationInMilliseconds>
    required: -52
    optional: 0
    bool: True
    short: -i
    long: --replica-restart-wait-duration-in-milliseconds
    description: the milliseconds of the replica restart wait duration
  - flags: -d --quorum-loss-wait-duration-in-milliseconds <quorumLossWaitDurationInMilliseconds>
    required: -48
    optional: 0
    bool: True
    short: -d
    long: --quorum-loss-wait-duration-in-milliseconds
    description: the milliseconds of the quorum loss wait duration
  - flags: -t --stand-by-replica-keep-duration-in-milliseconds <standByReplicaKeepDurationInMilliseconds>
    required: -53
    optional: 0
    bool: True
    short: -t
    long: --stand-by-replica-keep-duration-in-milliseconds
    description: the milliseconds of the stand by replica keep duration
- name: delete
  description: Delete service
  usage: '[options] [serviceName]'
  filePath: commands/servicefabric/serviceFabricService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --service-name <serviceName>
    required: -19
    optional: 0
    bool: True
    short: -n
    long: --service-name
    description: the name of the service
- name: resolve
  description: Resolve service
  usage: '[options] [serviceName]'
  filePath: commands/servicefabric/serviceFabricService._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n --service-name <serviceName>
    required: -19
    optional: 0
    bool: True
    short: -n
    long: --service-name
    description: the name of the service
  - flags: -t --partition-key-type <partitionKeyType>
    required: -25
    optional: 0
    bool: True
    short: -t
    long: --partition-key-type
    description: the type of the partition key, values are [Singleton|Int64Range|Named]
  - flags: -k --partition-key-value <partitionKeyValue>
    required: -26
    optional: 0
    bool: True
    short: -k
    long: --partition-key-value
    description: the value of the partition key
  - flags: -r --previous-rsp-version <previousRspVersion>
    required: -27
    optional: 0
    bool: True
    short: -r
    long: --previous-rsp-version
    description: the version of the previous rsp
  - flags: --select <fields>
    required: -10
    optional: 0
    bool: True
    long: --select
    description: select fields to show, call without this parameter to see all fields
name: service
description: Commands to manage your service
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Service%20Management/servicefabric/service.yml
  update_at: 12/30/2016 4:45 AM
  ms.date: 12/30/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/a279321f0a73c72eb40e8107a6580f28e289cd66/azure-xplat/Azure%20Service%20Management/servicefabric/service.yml
  ms.topic: reference
