### YamlMime:AzureXplatCli
commands:
- name: show
  description: Gets the remote login settings for the specified node
  usage: '[options] [pool-id] [node-id]'
  filePath: commands/batch/batch.node._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -p, --pool-id <pool-Id>
    required: -15
    optional: 0
    bool: True
    short: -p
    long: --pool-id
    description: the id of the pool that contains the compute node
  - flags: -i, --node-id <node-Id>
    required: -15
    optional: 0
    bool: True
    short: -i
    long: --node-id
    description: the id of the compute node for which you want to get the remote login settings
  - flags: -a, --account-name <account-name>
    required: -20
    optional: 0
    bool: True
    short: -a
    long: --account-name
    description: the Batch account name
  - flags: -k, --account-key <account-key>
    required: -19
    optional: 0
    bool: True
    short: -k
    long: --account-key
    description: the Batch account key
  - flags: -u, --account-endpoint <account-endpoint>
    required: -24
    optional: 0
    bool: True
    short: -u
    long: --account-endpoint
    description: the Batch account URL
name: remote-login-settings
description: The remote login settings for a Batch compute node
usage: '[options] [command]'
Metadata:
  ms.topic: reference
  open_to_public_contributors: true
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/batch/batch.node._js
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/batch/batch.node._js
  update_at: 5/4/2016 6:55 PM
  ms.date: 5/4/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/1066e83f59170a46b1f6ab3f118478dac874aea9/lib/commands/batch/batch.node._js

