### YamlMime:AzureXplatCli
commands:
- name: set
  description: Set webapp Container configurations (available only for linux webapps)
  usage: '[options] <resource-group> <name>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp
  - flags: -r --url <url>
    required: -10
    optional: 0
    bool: True
    short: -r
    long: --url
    description: the container registry server url
  - flags: -u --username <username>
    required: -15
    optional: 0
    bool: True
    short: -u
    long: --username
    description: the container registry server username
  - flags: -p --password <password>
    required: -15
    optional: 0
    bool: True
    short: -p
    long: --password
    description: the container registry server password
  - flags: -c --custom-image-name <custom-image-name>
    required: -24
    optional: 0
    bool: True
    short: -c
    long: --custom-image-name
    description: the container custom image name and optionally the tag name
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: list
  description: List Container configurations  (available only for linux webapps)
  usage: '[options] <resource-group> <name>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: delete
  description: Delete all webapp Container configurations (available only for linux webapps)
  usage: '[options] <resource-group> <name>'
  filePath: commands/arm/webapp/webapp.config._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -g --resource-group <resource-group>
    required: -21
    optional: 0
    bool: True
    short: -g
    long: --resource-group
    description: the name of the resource group
  - flags: -n --name <name>
    required: -11
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the webapp
  - flags: --slot <slot>
    required: -8
    optional: 0
    bool: True
    long: --slot
    description: the name of the slot
  - flags: -s --subscription <subscription>
    required: -19
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: container
description: Commands to manage your Azure webapps container configurations
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/webapp/config/container/container.yml
  update_at: 12/26/2016 8:07 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6160027b77dbfdec40c6aee3f83b1ab23cc14628/azure-xplat/Azure%20Resource%20Management/webapp/config/container/container.yml
  ms.topic: reference
  ms.prod: 
  ms.technology: 
  author
  ms.author
  keywords
  manager
