### YamlMime:AzureXplatCli
commands:
- name: show
  description: Get an Application Gateway configuration
  usage: '[options] <name>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: export
  description: Export Application Gateway configuration to a file
  usage: '[options] <name> <file-path>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -t, --export-to-file <export-to-file>
    required: -22
    optional: 0
    bool: True
    short: -t
    long: --export-to-file
    description: the path to the file where configuration needs to be exported
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
- name: import
  description: Import Application Gateway configuration from a file
  usage: '[options] <name> <import-from-file>'
  filePath: commands/asm/network/network._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: -n, --name <name>
    required: -12
    optional: 0
    bool: True
    short: -n
    long: --name
    description: the name of the Application Gateway
  - flags: -t, --import-from-file <import-from-file>
    required: -24
    optional: 0
    bool: True
    short: -t
    long: --import-from-file
    description: the path to the configuration file
  - flags: -s, --subscription <subscription>
    required: -20
    optional: 0
    bool: True
    short: -s
    long: --subscription
    description: the subscription identifier
name: config
description: Commands to manage Application Gateway configuration
usage: '[options] [command]'
Metadata:
  ms.topic: reference
  open_to_public_contributors: true
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/asm/network/network._js
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/asm/network/network._js
  update_at: 2/16/2016 8:20 AM
  ms.date: 2/16/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/ad831194034c67c12c577182ff8519f2a62f3200/lib/commands/asm/network/network._js

