### YamlMime:AzureXplatCli
commands:
- name: set
  description: "Set application-gateway-backend-address-pools in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"applicationGatewayBackendAddressPools\" : {\r\n             \"id\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --index <index>
    required: -9
    optional: 0
    bool: True
    long: --index
    description: 'Indexer: index.'
  - flags: --ip-configurations-index <ip-configurations-index>
    required: -27
    optional: 0
    bool: True
    long: --ip-configurations-index
    description: 'Indexer: ip-configurations-index.'
  - flags: --network-interface-configurations-index <network-interface-configurations-index>
    required: -42
    optional: 0
    bool: True
    long: --network-interface-configurations-index
    description: 'Indexer: network-interface-configurations-index.'
  - flags: --value <value>
    required: -9
    optional: 0
    bool: True
    long: --value
    description: The input string value for the indexed item.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the input string, i.e. str, for parameters to a JSON object, e.g. JSON.parse(str).
  - flags: --id <id>
    required: -6
    optional: 0
    bool: True
    long: --id
    description: Set the id value.
- name: delete
  description: "Remove application-gateway-backend-address-pools in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"applicationGatewayBackendAddressPools\" : {\r\n             \"id\":\"\"\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --index <index>
    required: -9
    optional: 0
    bool: True
    long: --index
    description: 'Indexer: index.'
  - flags: --ip-configurations-index <ip-configurations-index>
    required: -27
    optional: 0
    bool: True
    long: --ip-configurations-index
    description: 'Indexer: ip-configurations-index.'
  - flags: --network-interface-configurations-index <network-interface-configurations-index>
    required: -42
    optional: 0
    bool: True
    long: --network-interface-configurations-index
    description: 'Indexer: network-interface-configurations-index.'
  - flags: --id
    required: 0
    optional: 0
    bool: True
    long: --id
    description: Remove the id value.
name: application-gateway-backend-address-pools
description: Commands to configure application-gateway-backend-address-pools of vmss in config file.
usage: '[options] [command]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/vmss/config/application-gateway-backend-address-pools.yml
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob//azure-xplat/Azure%20Resource%20Management/vmss/config/application-gateway-backend-address-pools.yml
  ms.topic: reference
