### YamlMime:AzureXplatCli
commands:
- name: create
  description: Generate virtualMachineScaleSetsCreateOrUpdate parameter string or files.
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
- name: patch
  description: Command to patch virtualMachineScaleSetsCreateOrUpdate parameter JSON file.
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --operation <operation>
    required: -13
    optional: 0
    bool: True
    long: --operation
    description: 'The JSON patch operation: add, remove, or replace.'
  - flags: --path <path>
    required: -8
    optional: 0
    bool: True
    long: --path
    description: 'The JSON data path, e.g.: "foo/1".'
  - flags: --value <value>
    required: -9
    optional: 0
    bool: True
    long: --value
    description: The JSON value.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the JSON value to object.
name: config
description: Commands to manage configuration of virtual-machine-scale-sets in the parameter file.
usage: '[options] [command]'
Metadata:
  original_content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/vmss/config/config.yml
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/vmss/config/config.yml
  update_at: 12/26/2016 5:40 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/b1f9f2de97a35fb1e5a719e3e38a2f2848bfe692/azure-xplat/Azure%20Resource%20Management/vmss/config/config.yml
  ms.topic: reference
  ms.prod: 
  ms.technology: 
  author
  ms.author
  keywords
  manager
