### YamlMime:AzureXplatCli
commands:
- name: set
  description: "Set win-rm in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"winRM\" : {\r\n             \"listeners\":[\r\n               {\r\n                 \"protocol\":null,\r\n                 \"certificateUrl\":\"\"\r\n               }\r\n             ]\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --parse
    required: 0
    optional: 0
    bool: True
    long: --parse
    description: Parse the input string, i.e. str, for parameters to a JSON object, e.g. JSON.parse(str).
  - flags: --listeners <listeners>
    required: -13
    optional: 0
    bool: True
    long: --listeners
    description: Set the listeners value.
- name: delete
  description: "Remove win-rm in config string or files, e.g. \r\n         {\r\n           ...\r\n           \"winRM\" : {\r\n             \"listeners\":[\r\n               {\r\n                 \"protocol\":null,\r\n                 \"certificateUrl\":\"\"\r\n               }\r\n             ]\r\n           }\r\n           ...\r\n         }\r\n\r\n         There are two sets of commands:\r\n           1) function commands that are used to manage Azure resources in the cloud, and \r\n           2) parameter commands that generate & edit input files for the other set of commands.\r\n         For example, 'vmss show/list/stop' are the function commands that call get, list and stop operations of \r\n         virtual machine scale set, whereas 'vmss config * generate/create/set/delete/add' commands \r\n         are used to configure the input parameter file. The 'vmss config' command takes a parameter \r\n         file as for the VM scale set configuration, and creates it online."
  usage: '[options]'
  filePath: commands/arm/compute/virtualMachineScaleSets._js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
  - flags: --parameter-file <parameter-file>
    required: -18
    optional: 0
    bool: True
    long: --parameter-file
    description: The parameter file path.
  - flags: --listeners
    required: 0
    optional: 0
    bool: True
    long: --listeners
    description: Remove the listeners value.
metadata:
  update_at: 12/30/2016 7:30 AM
  git_content_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/arm/compute/virtualMachineScaleSets._js  original_git_content_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/lib/commands/arm/compute/virtualMachineScaleSets._js  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/e782dc553e60b534e9d419a4511a9c54b4a47815/lib/commands/arm/compute/virtualMachineScaleSets._js  open_to_public_contributors: true
  ms.date: 12/30/2016
  ms.topic: reference
name: win-rm
description: Commands to configure win-rm of vmss in config file.
usage: '[options] [command]'
