### YamlMime:AzureXplatCli
commands: []
name: package
description: Commands to send your service package
usage: '[options]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/servicefabric/service/package/package.yml
  update_at: 12/28/2016 2:41 AM
  ms.date: 12/28/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/b5f1f48534a095fdf2852b504110001c0652d8b2/azure-xplat/Azure%20Resource%20Management/servicefabric/service/package/package.yml
  ms.topic: reference
