### YamlMime:AzureXplatCli
commands: []
name: package
description: Commands to send your service package
usage: '[options]'
Metadata:
  content_git_url: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/dev/azure-xplat/Azure%20Resource%20Management/servicefabric/service/package/package.yml
  update_at: 12/26/2016 8:33 AM
  ms.date: 12/26/2016
  gitcommit: https://github.com/Visual-Studio-China/azure-xplat-cli/blob/6e1e5d8c04f7446d91fcaca88663dcd6cdef9a3a/azure-xplat/Azure%20Resource%20Management/servicefabric/service/package/package.yml
  ms.topic: reference
