### YamlMime:AzureXplatCli
commands:
- name: list
  description: List config settings
  usage: '[options]'
  filePath: commands/config.js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
- name: delete
  description: Delete a config setting
  usage: '[options] <name>'
  filePath: commands/config.js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
- name: set
  description: Update a config setting
  usage: <name> <value>
  filePath: commands/config.js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
- name: mode
  description: Sets the cli working mode, valid names are 'arm' for resource manager and 'asm' for service management
  usage: '[options] <name>'
  filePath: commands/config.js
  options:
  - flags: -v, --verbose
    required: 0
    optional: 0
    bool: True
    short: -v
    long: --verbose
    description: use verbose output
  - flags: -vv
    required: 0
    optional: 0
    bool: True
    long: -vv
    description: more verbose with debug output
  - flags: --json
    required: 0
    optional: 0
    bool: True
    long: --json
    description: use json output
name: config
description: Commands to manage your local settings
usage: '[options] [command]'
Metadata:
  update_at: 12/30/2016 7:37 AM
  open_to_public_contributors: false
  ms.date: 12/30/2016
  ms.topic: reference